// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agzzwwkrnidjvxxlofgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnenp3d2tybmlkanZ4eGxvZmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTczNTAsImV4cCI6MjA2MjI5MzM1MH0.K3I2-WQqhM9yaoXNcit5qrEd1JwzqjrTaCJykPrd4Es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);